name: Windows

on: [push]

jobs:
  Build-for-Windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build AmneziaWG tools
      run: |
        cmd /c build.cmd
        mkdir build
        move x64 build\x64
        move x86 build\x86
        move arm64 build\arm64

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        retention-days: 1
        name: windows-amneziawg-tools
        path: build

  GitHub-Release:
    name: GitHub Release
    needs: Build-for-Windows
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Calculate checksums
        run: for file in $(find ./ -name '*.exe' ); do openssl dgst -sha256 -r "$file" | awk '{print $1}' > "${file}.sha256"; done

      - name: Zip files
        run: for file in *; do zip -r ${file%.*}.zip  $file; done

      - name: Upload binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: windows-amneziawg-tools.zip
          tag: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          overwrite: true
          file_glob: true
